# Generated by Django 3.2.5 on 2021-07-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Netflix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('genre', models.TextField(choices=[('로맨스', '로맨스'), ('호러/스릴러', '호러/스릴러'), ('SF/판타지', 'SF/판타지'), ('버라이어티/예능', '버라이어티/예능'), ('애니메이션', '애니메이션'), ('다큐멘터리', '다큐멘터리')])),
                ('score', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='netflix/')),
            ],
        ),
    ]
